version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fluxride-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluxride_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: fluxride-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:7-alpine
    container_name: fluxride-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  ride-service:
    build:
      context: ./ride-service
    container_name: fluxride-ride-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fluxride_rides?schema=public
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka

  payment-service:
    build:
      context: ./payment-service
    container_name: fluxride-payment-service
    ports:
      - "3004:3004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fluxride_db?schema=public
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka

  user-db:
    image: postgres:15-alpine
    container_name: fluxride-user-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: fluxride-user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@user-db:5432/user_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=#Bexon12
      - JWT_REFRESH_SECRET=super_secret_refresh_key
      - NODE_ENV=development
    command: sh -c "npx prisma migrate deploy && npm start"
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_started

  driver-db:
    image: postgres:15-alpine
    container_name: fluxride-driver-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driver_db
    volumes:
      - driver_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d driver_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  driver-service:
    build:
      context: ./driver-service
    container_name: fluxride-driver-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@driver-db:5432/driver_db?schema=public
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=#Bexon12
      - NODE_ENV=development
    command: sh -c "npx prisma migrate deploy && npm start"
    depends_on:
      driver-db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

  notification-service:
    build:
      context: ./notification-service
    container_name: fluxride-notification-service
    ports:
      - "3005:3005"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

volumes:
  postgres_data:
  redis_data:
  user_db_data:
  driver_db_data:
